// React Task/my-app/src/Components/Home/Book.tsx
import { BookModel } from "../../Model/BookModel";
import "./book.style.scss";
import { useNavigate } from "react-router-dom";
import { Button } from "reactstrap";

interface BookProps {
  book: BookModel;
}

const Book = ({ book }: BookProps) => {
  const navigate = useNavigate();
  const routeChange = () => {
    navigate("/" + book._name, { state: book });
  };

  return (
    <div className="card">
      <div className="card-body">
        <img src={book._image} alt="" onClick={routeChange} />
        <div>
          <h6 className="card-title text-center">{book._name}</h6>
          <p className="description">{book._description}</p>
          <Button
            className="btn-block"
            color="primary"
            size="sm"
            onClick={routeChange}
            // onClick={openBookDetails()}
          >
            Buy
          </Button>
        </div>
      </div>
    </div>
  );
};

export default Book;

// Angular Tasks/eCommerceApp/src/app/book/book.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Book } from '../book.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-book',
  templateUrl: './book.component.html',
  styleUrls: ['./book.component.css'],
})
export class BookComponent implements OnInit {
  constructor(private router: Router) {}

  ngOnInit(): void {}

  @Input() book!: Book;

  openBookDetails() {
    this.router.navigate([this.book.title]);
  }
}

<div class="card">
  <div class="card-body">
    <img [attr.src]="book.img" />
    <div>
      <h6 class="card-title text-center">{{ book.title }}</h6>
      <p>{{ book.description }}</p>
      <button class="btn btn-info btn-sm btn-block" (click)="openBookDetails()">
        Buy
      </button>
    </div>
  </div>
</div>
